language: java
jdk:
  - openjdk8

branches:
  only:
    - master
    - "/^v[0-9]+\\.[0-9]+/"

before_install:
  - chmod +x mvnw
  
install:
  - chmod +x ./setBranchVariable.sh
  - source ./setBranchVariable.sh
  
stages:
    - build
    - test

jobs:
    include:
        - stage: build
          name: Build ChillImport
          script: 
          - mvn install
          - mvn dockerfile:build
          after_success:
          - bash <(curl -s https://codecov.io/bash)
          - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"; fi'
          - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then mvn dockerfile:tag@tag-hash; fi'
          - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then mvn dockerfile:push@push-hash; fi'
          
          - 'if [ "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master"  ]; then mvn dockerfile:tag@tag-version; fi'
          - 'if [ "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master"  ]; then mvn dockerfile:push@push-version; fi'
          
          - 'if [ "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master"  ]; then mvn dockerfile:tag@tag-latest; fi'        
          - 'if [ "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master"  ]; then mvn dockerfile:push@push-latest; fi'
        - stage: test
          name: Phonito scan
          script: 
          - sudo wget https://phonito-public-artifacts.azureedge.net/scanner/phonito-scanner -O /usr/local/bin/phonito-scanner
          - sudo chmod +x /usr/local/bin/phonito-scanner
          - docker pull fraunhoferiosb/chillimport:$TAG
          - docker pull fraunhoferiosb/chillimport:latest
          - phonito-scanner -i fraunhoferiosb/chillimport:$TAG --fail-level CRITICAL
          - phonito-scanner -i fraunhoferiosb/chillimport:latest --fail-level CRITICAL

cache:
  directories:
  - '$HOME/.m2/repository'
  
services:
    - docker
    
env:
    global:
    # travis encrypt DOCKER_USERNAME=[username]
    - secure: GncB7ouKlnN9UWrmZZrTPEJn+NBFCKBK3rhHne50PHBtFKShjk+j/8qqm40ZqJAFZsCRPXxNJrbFvVe5I8Ozcre/PxnHlkR/5+Crp4vP3dCR9S5q8TfFtl3s+X2/OzSATEV0/J0dI5fQkL5/v8+GiXN9QnMEUwzsggumf3mC1loXBIvjhWXUZh1h2UJC3Jk05qCq2+mru08mQt7ygPnaQxihArCJKDMOSVklOf9EDWJcU3+agL1C+XRvcaRpsyaatnEmTQWrCWkW38ZCrIPH9ShsdEX6NFEyaJcGbcConkHvmpoWgQ5pnnieoOAx79wBqQnVOaPaLpDU5mI5el6pLuvINXxd0UDY4d/d6eU9YTQE1/7NdgTPp4W2TC+pUlCIYhzoK4R7d2NDi/KtWaNbBJ5+LMELTDy7oWEPEAi0Li/9VnqYms9hlOzKyL7WXUVeXK9vSS71ss0pylBtnzDUzvrn/aJMtKDMgalLNyCuSrlqFWPvL/zaUtxBEusxAW6yGx+RnxN5rrFWcHmQK6fbCpZ5Y6KiLeh508ZOQbld8uglvs2mKwX6tWZjLBvRJze8EjA9ZUSAU++SG3Nb+RbNONRvGxhE6umq0+fZ7fmxHxeDMy/xB1dlanD31JWJeiLzCd+gUD/LDYytfFviGkk79cEZdyLhwsPLc8Pg+3nJg7c=

    # travis encrypt DOCKER_PASSWORD=[password]
    - secure: peOdv4tTZc2+8EePaaHl5/RVGEsHRZThNckX7EpicGVWHnbvL8qldcwuttboSeGMT4kkwW27q28y9D3IU9NZEH6zd0P3rbwZhui/O4whmDRKgkfU3TqOTZfGge+6SGtVJLvJufR2DqI0jpko6ZQ/HU0PjlVPoIfO44ty1qaqIcgf2FU1ngVEiyvCVMUAlRrJDc3b6Dl0PkmNDZy42eV4sTKW0mTeBT2Ubb/kxrjcYHWIsbniuO5kGxXF+6OWRPkwhFAAMhm5gSdABRL/VwV0qK9o9ho3yBIgyQt6rdWxgIM0UB49lcChHn5L6OHXz0W4/d3UlTZdg1t5q6OJSNJ+cy9TF6Qwfcgi1t82m5lJu67gdl8QP4wthxr+nkfyTwRAyJSGLKw8lmSwsJrZlmhYazqhwBVrUY8XbwVtJl8HC764fU/uirTltgdZSxs0y1PID7WBF+Q+U/y/6O9pI8FZKyDlhqLd1OgxPC5dR44jCPy7Uj1sq+8onRSr9lvbm0uO3hYyIlpzdOj+QPdmKdERU/fsVFubV5fof6YGHA5SI9g4dynwzrb/wxw1a813wwUYyVtznncJQckhDqnKDp81VBsgKfgFdd31WgdlcR1HsS/YPdwgPkVb5S3eDW+1HVcjBVxHT3t9OvUlbU2XWP+a28ABwAdvHPAm01f6HQqL5cg=
    
    # travis encrypt PHONITO_API_TOKEN=[api_token]
    - secure: Jhz7XGqvBVhwqDRhB+qP52kOoy6rxj+medsBdfjThlhIa2WXhFJOxwRUk3raGGfTUrYDHxs6BJbvhQUr+iH8FYP+I6J60t8FfX1xO+SFskoL7WkrC/ulibcwcVMnLICKduyNXOgpOCt4p4FLojffFYukUL7qo0R7WMblsSALxPFPwIyPXgUT3EYTmWN3PbehdFTCQ3H5hkIknai5MZy0LoQ6MPpajzn3HmUK6Zebu82UtVgi61nfUjX+YD0rp7LRKS3ellws9bnK8sbAx9iP34mWYoHxyMkqalGdvZWBtJeBFFSBBYFMGzlRhHAXKYhIXZ18YkqUFAUDBg9wujQxCahmNpV+afFloiR4I/w0O5s+i94tcXSVLw1vJ3H5Q8yKV2a/aiAU+aBsldvvTx9l9mbxVXDTvbcMRnWnEZNuN9YExQIbKtthzn13gVP7bfiVkFJ2CwBGwJY7E3QK8WY8LNIvv+lCA9FFZ74zF0/qGCSmwIcrCSrg+MQfztmiznzUlHEhKjzCPdfel1koe3BCidwO7tPUnC9XsayaCiz82shyqrwq1Euw1LL2Gd8IN6w/HfGymgp2xcJBw52azBegZIWQwTkciHmwgh+2drTv6F+GT8S92lMsBEiyphDZjEm8v1PRaN2jCgrnEiOfTFWc5u9BfOzrFNdUijIVbJyBijg=
