language: java
jdk:
  - openjdk8

branches:
  only:
    - master
    - "/^v[0-9]+\\.[0-9]+/"

before_install:
  - chmod +x mvnw
  
install:
  - source ./setBranchVariable.sh
  
stages:
    - build    

jobs:
    include:
        - stage: build
          name: Build ChillImport
          script: 
          - mvn install
          - mvn dockerfile:build
          - source ./docker_test.sh
          after_success:
          - bash <(curl -s https://codecov.io/bash)
          - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"; fi'
          - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then mvn dockerfile:tag@tag-version; fi'
          - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then mvn dockerfile:tag@tag-hash; fi'
          - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then mvn dockerfile:tag@tag-latest; fi'
          - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then mvn dockerfile:push@push-version; fi'
          - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then mvn dockerfile:push@push-hash; fi'
          - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then mvn dockerfile:push@push-latest; fi'

cache:
  directories:
  - '$HOME/.m2/repository'
  
services:
    - docker
    
env:
    global:
    # travis encrypt DOCKER_USERNAME=[username]
    - secure: GncB7ouKlnN9UWrmZZrTPEJn+NBFCKBK3rhHne50PHBtFKShjk+j/8qqm40ZqJAFZsCRPXxNJrbFvVe5I8Ozcre/PxnHlkR/5+Crp4vP3dCR9S5q8TfFtl3s+X2/OzSATEV0/J0dI5fQkL5/v8+GiXN9QnMEUwzsggumf3mC1loXBIvjhWXUZh1h2UJC3Jk05qCq2+mru08mQt7ygPnaQxihArCJKDMOSVklOf9EDWJcU3+agL1C+XRvcaRpsyaatnEmTQWrCWkW38ZCrIPH9ShsdEX6NFEyaJcGbcConkHvmpoWgQ5pnnieoOAx79wBqQnVOaPaLpDU5mI5el6pLuvINXxd0UDY4d/d6eU9YTQE1/7NdgTPp4W2TC+pUlCIYhzoK4R7d2NDi/KtWaNbBJ5+LMELTDy7oWEPEAi0Li/9VnqYms9hlOzKyL7WXUVeXK9vSS71ss0pylBtnzDUzvrn/aJMtKDMgalLNyCuSrlqFWPvL/zaUtxBEusxAW6yGx+RnxN5rrFWcHmQK6fbCpZ5Y6KiLeh508ZOQbld8uglvs2mKwX6tWZjLBvRJze8EjA9ZUSAU++SG3Nb+RbNONRvGxhE6umq0+fZ7fmxHxeDMy/xB1dlanD31JWJeiLzCd+gUD/LDYytfFviGkk79cEZdyLhwsPLc8Pg+3nJg7c=

    # travis encrypt DOCKER_PASSWORD=[password]
    - secure: peOdv4tTZc2+8EePaaHl5/RVGEsHRZThNckX7EpicGVWHnbvL8qldcwuttboSeGMT4kkwW27q28y9D3IU9NZEH6zd0P3rbwZhui/O4whmDRKgkfU3TqOTZfGge+6SGtVJLvJufR2DqI0jpko6ZQ/HU0PjlVPoIfO44ty1qaqIcgf2FU1ngVEiyvCVMUAlRrJDc3b6Dl0PkmNDZy42eV4sTKW0mTeBT2Ubb/kxrjcYHWIsbniuO5kGxXF+6OWRPkwhFAAMhm5gSdABRL/VwV0qK9o9ho3yBIgyQt6rdWxgIM0UB49lcChHn5L6OHXz0W4/d3UlTZdg1t5q6OJSNJ+cy9TF6Qwfcgi1t82m5lJu67gdl8QP4wthxr+nkfyTwRAyJSGLKw8lmSwsJrZlmhYazqhwBVrUY8XbwVtJl8HC764fU/uirTltgdZSxs0y1PID7WBF+Q+U/y/6O9pI8FZKyDlhqLd1OgxPC5dR44jCPy7Uj1sq+8onRSr9lvbm0uO3hYyIlpzdOj+QPdmKdERU/fsVFubV5fof6YGHA5SI9g4dynwzrb/wxw1a813wwUYyVtznncJQckhDqnKDp81VBsgKfgFdd31WgdlcR1HsS/YPdwgPkVb5S3eDW+1HVcjBVxHT3t9OvUlbU2XWP+a28ABwAdvHPAm01f6HQqL5cg=
