version: '3.4'
services:
  chill-import:
    image: fraunhoferiosb/chillimport:latest

    ports:
            - "8000:8000"
    environment:
        - configPath="/data"
    volumes:
      - chill-import-volume:/data
      
volumes:
    chill-import-volume:
