name: Maven Pull Request Build

on:
  push:
    branches:
      - master
      - develop
      - develop-*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Cache maven repository
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven

    - name: Checkout Source
      uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build with Maven
      run: |
        export GIT_COMMIT_SHA=${GITHUB_SHA}
        mvn -B install
        mvn -B dockerfile:build
        echo "Tagging ${GIT_COMMIT_SHA}"
        mvn dockerfile:tag@tag-hash
        source ./docker_test.sh

    - name: Test with CodeCov
      run: |
        bash <(curl -s https://codecov.io/bash)

    - name: Push Docker Image - Tagged Commit
      if: startsWith(github.ref, 'refs/tags/')
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        export DOCKER_TAG=$(mvn -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec -q)
        export GIT_COMMIT_SHA=${GITHUB_SHA}
        echo "Tagging and Pushing '${DOCKER_TAG}' and ${GIT_COMMIT_SHA}"
        mvn dockerfile:tag@tag-version
        mvn dockerfile:push@push-version
        mvn dockerfile:push@push-hash

    - name: Push Docker Images - Master branch
      if: github.ref == 'refs/heads/master'
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        export DOCKER_TAG=$(mvn -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec -q)
        export GIT_COMMIT_SHA=${GITHUB_SHA}
        echo "Tagging and Pushing 'latest', '${DOCKER_TAG}' and ${GIT_COMMIT_SHA}"
        mvn dockerfile:tag@tag-version
        mvn dockerfile:tag@tag-latest
        mvn dockerfile:push@push-version
        mvn dockerfile:push@push-hash
        mvn dockerfile:push@push-latest

    - name: Push Docker Image - Other branch
      if: startsWith(github.ref, 'refs/heads/develop')
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        export version=$(mvn -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec -q)
        export DOCKER_TAG=${GITHUB_REF:11}-${version}
        export GIT_COMMIT_SHA=${GITHUB_SHA}
        echo "Tagging and Pushing '${DOCKER_TAG}' and ${GIT_COMMIT_SHA}"
        mvn dockerfile:tag@tag-version
        mvn dockerfile:push@push-version
        mvn dockerfile:push@push-hash
